/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerritoireRouteImport } from './routes/territoire'
import { Route as ProRouteImport } from './routes/pro'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as OpportunitesRouteImport } from './routes/opportunites'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as InvestisseursRouteImport } from './routes/investisseurs'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as CompetencesRouteImport } from './routes/competences'
import { Route as BusinessPlanRouteImport } from './routes/business-plan'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'

const TerritoireRoute = TerritoireRouteImport.update({
  id: '/territoire',
  path: '/territoire',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesRoute = OpportunitesRouteImport.update({
  id: '/opportunites',
  path: '/opportunites',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestisseursRoute = InvestisseursRouteImport.update({
  id: '/investisseurs',
  path: '/investisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetencesRoute = CompetencesRouteImport.update({
  id: '/competences',
  path: '/competences',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPlanRoute = BusinessPlanRouteImport.update({
  id: '/business-plan',
  path: '/business-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/admin/parametres',
  path: '/admin/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/business-plan': typeof BusinessPlanRoute
  '/competences': typeof CompetencesRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/investisseurs': typeof InvestisseursRoute
  '/newsletter': typeof NewsletterRoute
  '/opportunites': typeof OpportunitesRoute
  '/parcours': typeof ParcoursRoute
  '/pro': typeof ProRoute
  '/territoire': typeof TerritoireRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/business-plan': typeof BusinessPlanRoute
  '/competences': typeof CompetencesRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/investisseurs': typeof InvestisseursRoute
  '/newsletter': typeof NewsletterRoute
  '/opportunites': typeof OpportunitesRoute
  '/parcours': typeof ParcoursRoute
  '/pro': typeof ProRoute
  '/territoire': typeof TerritoireRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/business-plan': typeof BusinessPlanRoute
  '/competences': typeof CompetencesRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/dashboard': typeof DashboardRoute
  '/inscription': typeof InscriptionRoute
  '/investisseurs': typeof InvestisseursRoute
  '/newsletter': typeof NewsletterRoute
  '/opportunites': typeof OpportunitesRoute
  '/parcours': typeof ParcoursRoute
  '/pro': typeof ProRoute
  '/territoire': typeof TerritoireRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/business-plan'
    | '/competences'
    | '/confirm-email'
    | '/dashboard'
    | '/inscription'
    | '/investisseurs'
    | '/newsletter'
    | '/opportunites'
    | '/parcours'
    | '/pro'
    | '/territoire'
    | '/admin/leads'
    | '/admin/parametres'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/business-plan'
    | '/competences'
    | '/confirm-email'
    | '/dashboard'
    | '/inscription'
    | '/investisseurs'
    | '/newsletter'
    | '/opportunites'
    | '/parcours'
    | '/pro'
    | '/territoire'
    | '/admin/leads'
    | '/admin/parametres'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/business-plan'
    | '/competences'
    | '/confirm-email'
    | '/dashboard'
    | '/inscription'
    | '/investisseurs'
    | '/newsletter'
    | '/opportunites'
    | '/parcours'
    | '/pro'
    | '/territoire'
    | '/admin/leads'
    | '/admin/parametres'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  BusinessPlanRoute: typeof BusinessPlanRoute
  CompetencesRoute: typeof CompetencesRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  DashboardRoute: typeof DashboardRoute
  InscriptionRoute: typeof InscriptionRoute
  InvestisseursRoute: typeof InvestisseursRoute
  NewsletterRoute: typeof NewsletterRoute
  OpportunitesRoute: typeof OpportunitesRoute
  ParcoursRoute: typeof ParcoursRoute
  ProRoute: typeof ProRoute
  TerritoireRoute: typeof TerritoireRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminParametresRoute: typeof AdminParametresRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/territoire': {
      id: '/territoire'
      path: '/territoire'
      fullPath: '/territoire'
      preLoaderRoute: typeof TerritoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites': {
      id: '/opportunites'
      path: '/opportunites'
      fullPath: '/opportunites'
      preLoaderRoute: typeof OpportunitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investisseurs': {
      id: '/investisseurs'
      path: '/investisseurs'
      fullPath: '/investisseurs'
      preLoaderRoute: typeof InvestisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competences': {
      id: '/competences'
      path: '/competences'
      fullPath: '/competences'
      preLoaderRoute: typeof CompetencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-plan': {
      id: '/business-plan'
      path: '/business-plan'
      fullPath: '/business-plan'
      preLoaderRoute: typeof BusinessPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/admin/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  BusinessPlanRoute: BusinessPlanRoute,
  CompetencesRoute: CompetencesRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  DashboardRoute: DashboardRoute,
  InscriptionRoute: InscriptionRoute,
  InvestisseursRoute: InvestisseursRoute,
  NewsletterRoute: NewsletterRoute,
  OpportunitesRoute: OpportunitesRoute,
  ParcoursRoute: ParcoursRoute,
  ProRoute: ProRoute,
  TerritoireRoute: TerritoireRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminParametresRoute: AdminParametresRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
